# Build the manager binary
FROM registry.redhat.io/ubi9/go-toolset@sha256:da93d9c07bbc28a0cf5f436099a5b0acf2d079dc09564ffc08a6d300dd06adde AS builder
ARG TARGETOS
ARG TARGETARCH

USER root

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/

# Build
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} \
    GOEXPERIMENT=strictfipsruntime \
    go build -a -o manager cmd/main.go

# Use UBI minimal as the runtime base image
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:850143255ee0d1915f09aaa09f6ed31f24086ba605c323badfbefa95b8c52b0e
WORKDIR /
COPY --from=builder /workspace/manager .

USER 65532:65532
ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-agents-operator-rhel9" \
      name="rhoai/odh-agents-operator-rhel9" \
      description="Operator for deploying and lifecycle management of Agents and Tools" \
      summary="Operator for deploying and lifecycle management of Agents and Tools" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-agents-operator-rhel9" \
      io.k8s.description="odh-agents-operator-rhel9" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
