# Build the manager binary
FROM registry.redhat.io/ubi9/go-toolset@sha256:b2bc0c6c92c56dce575ed1b2dec1ec9f8b345a80ef5e74d9bfd530b6b354feeb AS builder
ARG TARGETOS
ARG TARGETARCH

USER root

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/

# Build
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} \
    GOEXPERIMENT=strictfipsruntime \
    go build -a -o manager cmd/main.go

# Use UBI minimal as the runtime base image
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:463cae32c6f6f5594b11a5c22de275016bd8545ce58a6373388e8b24f13fc15c
WORKDIR /
COPY --from=builder /workspace/manager .

USER 65532:65532
ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-agents-operator-rhel9" \
      name="rhoai/odh-agents-operator-rhel9" \
      description="Operator for deploying and lifecycle management of Agents and Tools" \
      summary="Operator for deploying and lifecycle management of Agents and Tools" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-agents-operator-rhel9" \
      io.k8s.description="odh-agents-operator-rhel9" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
